name: build java Images
on:
  push:
    branches: [main]
    paths:
      - "docker_images/java/**"
  pull_request:
    branches: [main]
    paths:
      - "docker_images/java/**"
  workflow_dispatch:

jobs:
  push:
    name: "skyports_images:java_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 8
          - 11
          - 16
          - 17
          - 21
          - 24
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
            image: tonistiigi/binfmt:qemu-v7.0.0-28
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./docker_images/java
          file: ./docker_images/java/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/pinont/skyports_images:java_${{ matrix.tag }}
            - uses: docker/login-action@v3